version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - "C:/Users/ADMIN/Desktop/U/Semestre 7/Ciencia de Datos en Producción/Jenkins_Financial_Risk_Auto:/workspace"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  jenkins_home: